import Head from "next/head";
import Header from "../components/Header";
import PatsTable from "../components/PatsTable";
import Mtable from "../components/Mtable";


// export async function getServerSideProps() {
//   const res = await fetch("http://localhost:3000/api/patient");
//   const data = await res.json();
//   // if (!data) {
//   //   return {
//   //     notFound: true,
//   //   }

//   return {
//     props: { list:data }, // will be passed to the page component as props
//   };
// }



export default function Home( ) {
  // const { setPatients } = useClinic();
  // {list ? setPatients(list) : null}
  return (
    <div className=" mx-2 bg-[#635e58e6]">
      <Head>
        <title>Pats Clinic</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>
      <PatsTable />
      {/* <Mtable/> */}
    </div>
  );
}
